import { Divider, Flex } from "@chakra-ui/react";
import Head from "next/head";
import Banner from "../components/Banner";
import PropertyCard from "../components/PropertyCard";
import { baseUrl, fetchApi } from "../utils/fetchAPI";

export default function Home({ propertiesForSale, propertiesForRent }) {
  // console.log({ propertiesForSale });
  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Banner
          imageUrl="https://realtor.vercel.app/_next/image?url=https%3A%2F%2Fbayut-production.s3.eu-central-1.amazonaws.com%2Fimage%2F145426814%2F33973352624c48628e41f2ec460faba4&w=640&q=75"
          purpose="rent a home"
          title="rental home for everyone"
          desc="Explore from Apartments, builder floors, villas
and more"
          buttonText="Explorer Renting"
          linkName="/search?purpose=for-rent"
        />
        <Flex flexWrap="wrap" gap="2" my="10">
          {propertiesForRent?.map((p) => (
            <PropertyCard key={p?.id} data={p} />
          ))}
        </Flex>
        <Divider my="10" />
        <Banner
          imageUrl="https://realtor.vercel.app/_next/image?url=https%3A%2F%2Fbayut-production.s3.eu-central-1.amazonaws.com%2Fimage%2F110993385%2F6a070e8e1bae4f7d8c1429bc303d2008&w=640&q=75"
          purpose="buy a home"
          title="find, buy & own your dream home"
          desc="Explore from Apartments, land, builder floors,
          villas and more"
          buttonText="Explorer Buying"
          linkName="/search?purpose=for-sale"
        />
        <Flex flexWrap="wrap" gap="2" my="10">
          {propertiesForSale?.map((p) => (
            <PropertyCard key={p?.id} data={p} />
          ))}
        </Flex>
      </>
    </>
  );
}

export const getStaticProps = async () => {
  const propertySale = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=9`);
  const propertyRent = await fetchApi(`${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=9`);

  return {
    props: {
      propertiesForSale: propertySale?.hits,
      propertiesForRent: propertyRent?.hits,
    },
  };
};
